name: Achievements
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write  # <--- İŞTE EKSİK OLAN SİHİRLİ SATIR BU
    steps:
      - uses: actions/checkout@v3
      - uses: Schweinepriester/github-profile-achievements@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: baloglu321
          commit: true
          AM_PM: false
          skin: flat
