name: Save-Trophies
on:
  schedule:
    # Günde 1 kez çalışır
    - cron: "0 0 * * *"
  workflow_dispatch:
  push: {branches: ["main", "master"]}

jobs:
  snapshot-trophies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Download Trophy Image
        run: |
          # Trophy servisine istek atıp resmi 'achievements.svg' olarak kaydeder
          # Buradaki linkte senin temanı ve ayarlarını hazırladım
          curl -o achievements.svg "https://github-profile-trophy.vercel.app/?username=baloglu321&theme=tokyonight&no-frame=true&column=7&margin-w=15"

      - name: Commit and Push
        run: |
          # Eğer dosyada değişiklik varsa (resim güncellendiyse) GitHub'a yükler
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add achievements.svg
          git commit -m "Update achievements snapshot" || exit 0
          git push
